'use client'

import { useState } from 'react'
import { BookOpen, Bot, ChevronRight, CircleAlert, Loader2, Send, ShieldCheck, Sparkles } from 'lucide-react'
import type { ChatResponse, Citation } from '@/types/corpus'

const suggestions = ['What does the Shamail corpus say about the Prophet ﷺ?', 'What descriptions of the Prophet ﷺ are recorded?', 'Show me information from the Seerah timeline.']

type Message = { role: 'user' | 'assistant'; content: string; citations?: Citation[]; classification?: string }

function SourceCard({ source, onClick }: { source: Citation; onClick: () => void }) {
  return <button onClick={onClick} className="group flex w-full items-center gap-3 rounded-xl border border-border/70 bg-background/60 p-3 text-left transition hover:border-primary/40 hover:bg-accent/50" aria-label={`View ${source.title}`}><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><BookOpen size={16} /></span><span className="min-w-0 flex-1"><span className="block text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">Approved {source.type} source</span><span className="block truncate text-sm font-medium">{source.title}</span><span className="text-xs text-muted-foreground">Entry #{source.id}</span></span><ChevronRight className="text-muted-foreground transition group-hover:translate-x-0.5" size={16} /></button>
}

export function SeerahChat() {
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [loading, setLoading] = useState(false)
  const [selected, setSelected] = useState<Citation | null>(null)
  const [error, setError] = useState('')

  async function submit(value = input) {
    const message = value.trim()
    if (!message || loading) return
    setMessages((current) => [...current, { role: 'user', content: message }]); setInput(''); setLoading(true); setError('')
    try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ message }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessages((current) => [...current, { role: 'assistant', content: data.answer, citations: data.citations, classification: data.classification }]) } catch (err) { setError(err instanceof Error ? err.message : 'Please try again.') } finally { setLoading(false) }
  }

  return <main className="mx-auto flex min-h-screen w-full max-w-5xl flex-col px-4 pb-32 sm:px-6">
    <header className="flex items-center justify-between border-b border-border/70 py-5"><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-2xl bg-primary text-primary-foreground shadow-sm"><Bot size={20} /></div><div><h1 className="font-serif text-lg font-semibold tracking-tight">Seerah Q&amp;A AI</h1><p className="text-xs text-muted-foreground">AI - Seerah Content Bot</p></div></div><div className="flex items-center gap-2 rounded-full border border-border bg-card px-3 py-1.5 text-xs font-medium text-muted-foreground"><ShieldCheck className="text-primary" size={14} /> Corpus grounded</div></header>
    <section className="flex flex-1 flex-col justify-center py-10 sm:py-16">
      {!messages.length ? <div className="mx-auto w-full max-w-2xl"><div className="mb-10 text-center"><div className="mx-auto mb-5 flex size-14 items-center justify-center rounded-2xl border border-primary/20 bg-primary/5 text-primary"><Sparkles size={24} /></div><h2 className="font-serif text-3xl font-semibold tracking-tight sm:text-4xl">Ask about the Seerah</h2><p className="mx-auto mt-3 max-w-lg text-pretty leading-6 text-muted-foreground">Explore answers drawn only from the approved Shamail and Seerah Timeline corpus, with a source for every factual response.</p></div><div className="grid gap-3 sm:grid-cols-3">{suggestions.map((suggestion) => <button key={suggestion} onClick={() => submit(suggestion)} className="rounded-2xl border border-border bg-card p-4 text-left text-sm leading-5 transition hover:-translate-y-0.5 hover:border-primary/40 hover:shadow-sm">{suggestion}<ChevronRight className="mt-3 text-primary" size={16} /></button>)}</div></div> : <div className="mx-auto flex w-full max-w-2xl flex-col gap-6">{messages.map((message, index) => <article key={index} className={message.role === 'user' ? 'ml-auto max-w-[88%]' : 'max-w-[94%]'}><div className={message.role === 'user' ? 'rounded-2xl rounded-br-md bg-primary px-4 py-3 text-sm leading-6 text-primary-foreground' : 'rounded-2xl rounded-bl-md border border-border bg-card px-4 py-4 text-sm leading-6 shadow-sm'} dir="auto">{message.content}</div>{message.citations?.length ? <div className="mt-2 grid gap-2">{message.citations.map((source) => <SourceCard key={`${source.type}-${source.id}`} source={source} onClick={() => setSelected(source)} />)}</div> : null}</article>)}{loading && <div className="flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="animate-spin" size={16} /> Searching approved sources…</div>}</div>}
    </section>
    {error && <div className="mx-auto mb-3 flex w-full max-w-2xl items-center gap-2 rounded-xl border border-destructive/30 bg-destructive/5 px-4 py-3 text-sm text-destructive"><CircleAlert size={16} />{error}</div>}
    <div className="fixed inset-x-0 bottom-0 z-10 border-t border-border/70 bg-background/95 px-4 pb-3 pt-3 backdrop-blur sm:static sm:border-0 sm:bg-transparent sm:p-0"><div className="mx-auto max-w-2xl"><form onSubmit={(event) => { event.preventDefault(); submit() }} className="flex items-end gap-2 rounded-2xl border border-border bg-card p-2 shadow-lg shadow-primary/5"><textarea value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); submit() } }} placeholder="Ask a question about the Seerah…" rows={1} className="min-h-11 flex-1 resize-none bg-transparent px-3 py-2.5 text-sm outline-none placeholder:text-muted-foreground" aria-label="Ask a question about the Seerah" /><button disabled={!input.trim() || loading} className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary text-primary-foreground transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40" aria-label="Send question">{loading ? <Loader2 className="animate-spin" size={18} /> : <Send size={18} />}</button></form><p className="mt-2 text-center text-[11px] leading-4 text-muted-foreground">AI-generated responses are limited to the approved Seerah corpus. This assistant does not provide fatwas or religious rulings.</p></div></div>
    {selected && <div role="dialog" aria-modal="true" className="fixed inset-0 z-20 flex items-end justify-center bg-foreground/20 p-4 sm:items-center" onClick={() => setSelected(null)}><div className="max-h-[80vh] w-full max-w-xl overflow-auto rounded-2xl border border-border bg-card p-5 shadow-xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-primary">Approved corpus source</p><h3 className="mt-1 font-serif text-xl font-semibold">{selected.title}</h3><p className="text-xs text-muted-foreground">{selected.type} · Entry #{selected.id}{selected.category ? ` · ${selected.category}` : ''}</p></div><button onClick={() => setSelected(null)} className="text-sm text-muted-foreground hover:text-foreground">Close</button></div><p className="mt-5 whitespace-pre-wrap text-sm leading-7" dir="auto">{selected.text}</p>{selected.hikayat && <><p className="mt-5 text-[11px] font-semibold uppercase tracking-[0.16em] text-muted-foreground">Additional corpus text</p><p className="mt-2 whitespace-pre-wrap text-sm leading-7" dir="auto">{selected.hikayat}</p></>}</div></div>}
  </main>
}
